### ISSUE TITLE
404 Fehler bei Sentry ignorieren

### ISSUE THREAD

**Issue by mimischi** [ClockGU/clock-backend#111]
Aktuell landen alle 404 Fehler bei Sentry. Einerseits sind das Crawler die stupide URLs durchbürsten. Andererseits typos von uns. Ich denke hat beides nichts auf Sentry zu suchen und verursacht nur Hintergrundrauschen.

**Comment by chgad** [comment]
Gelöst durch neue Sentry sdk.
