### ISSUE TITLE
Sortierung des Report Modles

### ISSUE THREAD

**Issue by chgad** [ClockGU/clock-backend#113]
In Fällen wie [diesem](https://github.com/ClockGU/clock-backend/blob/develop/api/utilities.py#L125) gehen wir bis jetzt davon aus, dass das Reprot QuerySet bereits nach `month_year` sortiert sind.
Dies ist aber **NICHT** der Fall.

Es gibt zwei Möglichkeiten:

1. An jeder Stelle, in der es wichtig ist die Reihenfolge nach `month_year` sortiert (chronologisch) zu erhalten, ein `.order_by("month_year")` dran zu hängen.

2. Allgemein dem Model das `ordering = ["month_year"]` vorzuschreiben.

**Comment by chgad** [comment]
Die 2. Möglichkeit verhindert das das vergessen des `.order_by()` calls zu ungewolltem Verhalten, Bugs oder Fehlern führt.

**Comment by mimischi** [comment]
Denke auch wir sollten eine Defaultorder vorgeben.  Wenn man es doch anders brauch kann man erneut ein `order_by` anhängen
