### ISSUE TITLE
Stundenzettel Übersetzung von F/K/U

### ISSUE THREAD

**Issue by sheepyhollow** [ClockGU/clock-backend#179]
Aktuell wird der Abwesenheitsgrund auf Englisch angezeigt, hier sollte eigentlich "Krankheit" oder "Urlaub" (bzw. "Feiertag") stehen.

**Comment by sheepyhollow** [comment]
Alternativ können wir mit den F/K/U-Kürzeln arbeiten; eine Legende gibt es ja.

**Comment by chgad** [comment]
Ich nehme dieses Issue mal als ansatzpunkt "Feiertag" als neuen Schichttyp einzuführen.
