### ISSUE TITLE
Schichten mit createError werden trotzdem gespeichert

### ISSUE THREAD

**Issue by sheepyhollow** [ClockGU/clock-backend#204]
Die meisten Fehler werden vom Frontend abgefangen; es gibt aber noch seltene Konstellationen, in denen ein `non-field-error` vom Backend geworfen wird, z.B. `A shift set in the future must be labeled as scheduled.`

Diese Schicht wird offenbar trotzdem gespeichert.

**Comment by sheepyhollow** [comment]
Das Problem trat häufig auf, als `reviewed` bei wiederholenden Schichten in Vergangenheit noch nicht korrekt gesetzt wurde. Daraus resultierten teils enorme Anzahlen überflüssiger Schichten, da die User mehrfach auf "Speichern" geklickt haben und das ShiftForm wegen des Fehlers nicht geschlossen wurde.

**Comment by SoerenGrieger** [comment]
Ich würde das schließen, da wir
1. alle Schichten in der Zukunft immer als was_reviewed=false speichern
2. Serientermine nur noch zukünftige Schichten erstellen
3. die Validations im Frontend sehr gut funktionieren

**Comment by sheepyhollow** [comment]
Wenn dem so ist, dann zu damit. Die Validations gab es ja vorher nicht. Vielleicht gibt es noch irgendwelche Edge-Cases, aber das zeigen die Staging-Tests.
