### ISSUE TITLE
Überlappende Schichten sind erstellbar

### ISSUE THREAD

**Issue by chgad** [ClockGU/clock-backend#21]
Momentan gibt es keine Logik die beim erstellen einer Schicht checkt ob während des gleichen Zeitraumes schon eine Schicht stattfand.

**Comment by mimischi** [comment]
Wir hatten doch gesagt, dass das erlaubt ist und nur beim Erstellen eines Reports solch ein Check stattfindet.

**Comment by chgad** [comment]
AH korrekt. Habe ich vergessen. Dann ist alles klar.
