### ISSUE TITLE
Report creation

### ISSUE THREAD

**Issue by chgad** [ClockGU/clock-backend#247]
Bei der Report creation passiert folgendes:

Erstellt man einen Vertrag der Beispiels weise am 1. Aprill 2022 startet und am 30. April 2022 endet, werden Reports erstllt bis "heute" (bspw. März 2023).

[Hier](https://github.com/ClockGU/clock-backend/blob/e97279fa40a4c9977bc44cff1986ed3c0d92525f/api/utilities.py#L81) muss unterschieden werden ob `contract.end_date < today` und nur bis `end_date` interiert werden.

**Comment by SoerenGrieger** [comment]
done in #248
