### ISSUE TITLE
Github Workflow bei PR merging deploy auf Staging

### ISSUE THREAD

**Issue by SoerenGrieger** [ClockGU/clock-backend#258]
Ein PR sollte automatisch beim Merge in Develop auf staging deployed werden.
Nach Möglichkeit mit der Option einen Deploy auszuschließen, ähnlich der Funktionalität der closing keywords zum schließen eines Issues beim Merge des PR.

**Comment by SoerenGrieger** [comment]
Auch für das Frontend einführen

**Comment by SoerenGrieger** [comment]
Rechercheergebnis:
Als Basistool nutzen wir dafür am Besten [scp-action](https://github.com/appleboy/scp-action). Die Doku für die dafür notwendigen Secrets befindet sich [hier](https://docs.github.com/en/actions/security-guides/encrypted-secrets) und mit den [Conditions](https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution) lässt sich ggf. ein keyword aus dem PR auslesen. Also Keyword würde ich `no-deploy` vorschlagen

**Comment by sheepyhollow** [comment]
Vielleicht lässt sich hier was abgucken: https://github.com/zentrumnawi/solid-frontend/tree/dev/.github/workflows

**Comment by SoerenGrieger** [comment]
ja, thx, da habe ich schon geschaut, allerdings hat das aus meiner Perspektive eine für mich nicht nachvollziehbare Designentscheidung: es wird einmal alles auf dem Server gelöscht und dann einfach nur die Daten dort wieder hin transferiert.

Ähnlich würde bei folgenden Optionen vorgegangen werden:

- [GitHub Action for GitHub Push](https://github.com/ad-m/github-push-action)
- [github-action-push-to-another-repository](https://github.com/cpina/github-action-push-to-another-repository)

Wenn wir bisher unseren Code händisch verschieben tun wir das im Case Staging z.B. mit `git push staging develop:master`.
Mein aktueller Gedanke/Plan ist:
Warum sollte das nicht 1zu1 genau so umsetzbar sein? Man baut einfach eine Action die genau diesen Befehl auf der Kommandozeile auch eingibt. Das hätte den charmanten Mehrwert, dass nicht brutal gelöscht wird, sondern schön smooth gepusht wird, wie wir es bisher umsetzen.

Zu der Option einen Deploy auszuschließen hätte ich den Vorschlag, dass einfach jeder PR das Label `deploy` bekommt und sollte jmd das nicht wünschen für diesen PR, dann muss er das Label aktiv löschen. Erste Hinweise zur Umsetzung in dieser Doku zu [Conditions](https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution).

Zu Sicherheit sollte noch geprüft bzw konfiguriert werden, dass es immer nur einen Deploy Prozess geben darf. Später startende Deploys müssen warten, die Reihenfolge ist first come first serve.

**Comment by SoerenGrieger** [comment]
Funktionalität nicht mehr gewollt. Wir lösen das intern mit einem neuen Workflow:
Einem Release geht einem 1 einwöchigem Staging Freeze voraus, wo Staging ausgiebig getestet wird und auf Develop nur Fixes gepusht werden dürfen.
