### ISSUE TITLE
Geleistete Arbeitszeit nur Arbeitszeit aus akutem Monat

### ISSUE THREAD

**Issue by SoerenGrieger** [ClockGU/clock-backend#264]

**Comment by SoerenGrieger** [comment]
Nach Anpassung sieht die Auflistung im Report wie folgt aus:
![image](https://github.com/ClockGU/clock-backend/assets/50986166/431d81bd-5e7d-42dd-a091-02d2351f7dea)

Analog dazu die FortschrittsCard im Dashboard:
![image](https://github.com/ClockGU/clock-backend/assets/50986166/838bbd65-bb54-4ff0-9ced-629bb9b79f11)

**Comment by SoerenGrieger** [comment]
Und der Stundenzettel sieht genau so aus:
![image](https://github.com/ClockGU/clock-backend/assets/50986166/a9df289a-b47b-4bbb-87ec-ecf2f680bb58)

**Comment by sheepyhollow** [comment]
Ja, das passt so.
