### ISSUE TITLE
Update_reports - Unsinnige Query

### ISSUE THREAD

**Issue by chgad** [ClockGU/clock-backend#268]
Ich weiß nicht was ich mir damals [dabei](https://github.com/ClockGU/clock-backend/blob/054610d31ecc77a7ab32278da10518e36f45deb9/api/management/commands/update_reports.py#L27)

gedacht habe aber es ist Quatsch.
Dieser Query filtert nur verträge die vor `start_date` beginnen UND nach `start_date` enden. Quasi nur Verträge die währen des angegebenen Monats laufen. Da das ein reine Management command ist sollte er auch so genutzt werden - mit Vorsicht.

Damit `start_month` und `start_year` hier wirklich Sinn ergeben schlage ich folgenden Query vor:

        contract_qs = Contract.objects.filter(
            user__is_active=True,
            user__is_staff=False,
            start_date__gte=start_month_year,
        )

**Comment by SoerenGrieger** [comment]
Ich sehe nichts, was dagegen spricht. Dann können wir auch das toDo aus dem Code nehmen mit den optionalen Argumenten?

**Comment by chgad** [comment]
Make it so.

Sören Grieger ***@***.***> schrieb am Fr., 26. Mai 2023,
09:33:
