### ISSUE TITLE
Report Objekte erstellen

### ISSUE THREAD

**Issue by chgad** [ClockGU/clock-backend#27]
Momentan wird nirgends im Backend tatsächlich ein Report Objekt erstellt.

Dies muss sich selbstverständlich ändern :

1. Szenario/Userstory:
Ein User - nenne wir ihn Mark - Registriert sich zum ersten mal, erstellt seinen einzigen Vertrag und gelangt nun zur Übersicht "Für welchen Vertrag arbeitest du heute".
Er klickt selbstverständlich auf den einzig möglichen. Hier sollte er nun zu einer Übersicht kommen die ihm seinen Momentanen Fortschritt anzeigt. Um das aber anzuzeigen ruft das Frontend den aktuellen Report über `api/reports/get_current` ab.

Dieser Endpoint würde einen `404 NOT FOUND` als Response geben (jetziger Stand).
Hier könnte man sehr leicht ein `get_or_create()` einbauen um entweder einen frisches/leeres Report Objekt für den momentanen Monat zuerstellen und zurück zu geben oder den tatsächlichen Report zurückzugeben.

2. Szenario/Userstory:
Ein User - nenne wir ihn Mark - möchte eine Schicht in einem Monat in der Zukunft planen.

Hier müsste dann beim Speichern der Schicht ein Report Objekt für den betreffenden Monat erstellt werden. Dies bedeutet ein `get_or_create()` in der `save()` Logik des SchiftSerializer's.

Allgemein : 

Beide Szenario's können allgemein damit abgefangen werden das man beim Erstellen eines Vertrages für die gesammte Dauer (alle Monate) direkt Report Objekte erstellt.
Als Beispiel siehe [hier](https://stackoverflow.com/q/10141045/8226216).

**Comment by chgad** [comment]
Nach guter überlegung und Rücksprache mit @mimischi sind wir zu dem Entschluss gekommen das die Lösungen für Szenario 1 und 2 jeweils eine implementierung an einer anderen Stelle benötigt.

1. in der View Action von `api/get_current` 

2. In der noch unberührten `save()` Methode des ShiftSerializers.

Des Weiteren erstellt die "Allgemeine" zu Lösung zuviele Report Objekte im Voraus was die später implementierte "Update von Reports" Logik erschwert.

Wir sind also zu folgendem entschluss gekommen:

- Beim erstellen eines `Contract` Objektes (einem Vertrag) wird wie [hier](https://stackoverflow.com/q/10141045/8226216) ein `Report` Objekt für den Monat erstellt, in dem der Vertrag beginnt. 
Somit ist gesichert, dass die Userstory des 1. Szenarios flüssig durch läuft und `api/get_current` den gerade erstellten Report zurückgibt.

- Das 2. Szenario ist in dahin abgedeckt, dass wir uns darauf geeinigt haben das geplante Schichten `was_reviewed = False` KEINEN Report benötigen. Dies ist sinnvoll, da nach den [Businessrules](https://clockgu.gitbook.io/technical/business-rules/shifts) diese Schichten generell nicht bei einem Report beachtet werden.

- Um Reports für folgende Monate (nach Vertragserstellung) anzulegen soll eine automatische Lösung gefunden werden (siehe  #28). Diese Entscheidung wurde entgegen der Alternative beschlossen den Aktuellen Arbeitsstand "on-the-fly" immer neu zu berechnen und ein Report Objekt erst beim export zu erstellen. Grund dafür ist es dass wir ein persistentes Objekt bevorzugen.

**Comment by sheepyhollow** [comment]
An welcher Stelle findet denn die "Fixierung" des Reports statt? Man soll ja vergangene Reports nach Abgabe nicht mehr nachträglich ändern können.

**Comment by chgad** [comment]
> An welcher Stelle findet denn die "Fixierung" des Reports statt? Man soll ja vergangene Reports nach Abgabe nicht mehr nachträglich ändern können.

@sheepyhollow das ist Offtopic.

**Comment by chgad** [comment]
Erledigt in #33.
