### ISSUE TITLE
Django 4.2 und Postgres >= 12.0

### ISSUE THREAD

**Issue by SoerenGrieger** [ClockGU/clock-backend#298]
Django muss noch auf die neuste Version (4.2) gehoben werden. In dem Zuge ist allerdings auch ein Update der produktiven DB nötig, die aktuell auf 11.6 läuft. Django 4.2 unterstützt nur Postgres 12 und größer. Ich schlage vor in diesem Zuge auf Postgres 14 oder 15 zu gehen.

**Comment by SoerenGrieger** [comment]
Anleitung zum Update ist [hier](https://github.com/dokku/dokku-postgres#upgrade-service--to-the-specified-versions) zu finden

**Comment by chgad** [comment]
Closed by #327
