### ISSUE TITLE
Stundenzettel Notizen - Code 1 nicht angezeigt

### ISSUE THREAD

**Issue by chgad** [ClockGU/clock-backend#335]
Anlegen einer 10 Stunden Schicht ohne Pause, zieht zwar 45 Minuten Pause ab Meldet aber keinen Code 2 in den Notizen.

Code 2 wird [hier](https://github.com/ClockGU/clock-backend/blob/4c28160193142e63b1a44eca3997596e13e6ccb6/api/views.py#L340) ermittelt, nachdem die Pausenzeit bereits auf die Minimal werte geändert wurden. Somit wird Code 2 nie
hinzugefügt.

Um dies korrekt zu evaluieren muss die ursprünglihce work- und breaktime benutzt werden.

Im Gleichzuge schalge ich die Bezeichnung von Code 2 zu "Automatischer Pausenzeitabzug, Pausenzeit nicht ausreichend" ändern.

**Comment by sheepyhollow** [comment]
Ok so, nur die Formulierung umdrehen:

"Pausenzeit nicht ausreichend, automatischer Pausenzeitabzug"

(wegen Kausalität)
