### ISSUE TITLE
Export des Stundenzettels

### ISSUE THREAD

**Issue by chgad** [ClockGU/clock-backend#34]
Eine der Kernfunktionalitäten des Services ist es einen Stundenzettel über alle, bis zum Zeitpunkt des Exports gespeicherten, Schichten anzufertigen.

Dieses Feature sollte wie folgt verwirklicht werden:

- [ ] erstelle ein HTML-Template `report_template.html` welches den aktuellen [Stundenzettel](www.uni-frankfurt.de/68252342/Arbeitszeitkonto_SHK.xlsx) abbildet

- [ ]  erstelle eine View die alle Daten für dieses template aggregiert, url : `export_report/<uuid>`

- [ ] diese View soll über [Headless Chrome](https://github.com/lazyatom/dokku-chrome) aufgerufen werden und aus der HTML Seite ein PDF erstellt werden

- [ ] Dieses PDF soll als Response zurückgegeben werden

**Comment by mimischi** [comment]
Erstmal zwei grundlegende Dinge:

1) Wir erstellen ein HTML Template und nutzen die Django Templating Engine um kurzerhand Variablen zu ersetzen (Name, Monat, Stundenzahl, Schichten, ...).
2) Es gibt eine View, `export/<uuid>`, welche das HTML Template nimmt, mit Daten füttert und nur im Browser rendert.
3) Es gibt einen API Endpunkt `export_report/<uuid>`, der den Chrome Headless Job startet, welcher die View aus Punkt 2 aufruft und als PDF rendert.

In der naiven Annahme funktioniert Schritt 2 ohne Authentifizierung. Da man die `<uuid>` nicht erraten kann, sollte das auch in Ordnung sein. Trotzdem denke ich, dass wir die View schlussendlich mit einem `API_KEY` o.ä. sichern sollten. `API_KEY` daher, weil der Aufruf der View durch Headless Chrome stattfinden wird und nicht durch den authentifizierten User.

Der Ablauf sollte dann wie folgt sein:

1) User klickt auf "Export".
2) Das Frontend stellt eine Anfrage an `api/export/<uuid>`.
3) Hier wird nun Headless Chrome aufgerufen, welches die URL `export_report/<uuid>` rendern soll.
4) `export_report/<uuid>` gibt eine HTML Seite mit ausgefüllten Daten wieder.
5) Headless Chrome rendert die PDF.
6) Die PDF wird entweder direkt zum Download angeboten oder vorerst nur gespeichert und im Frontend in einer Liste angezeigt.

**Comment by chgad** [comment]
> In der naiven Annahme funktioniert Schritt 2 ohne Authentifizierung. Da man die <uuid> nicht erraten kann, sollte das auch in Ordnung sein. Trotzdem denke ich, dass wir die View schlussendlich mit einem API_KEY o.ä. sichern sollten. API_KEY daher, weil der Aufruf der View durch Headless Chrome stattfinden wird und nicht durch den authentifizierten User.

Sollte ein User `api/export/<uuid>` aufrufen, würde es sowieso gegen den User authentifiziert. Prizipiell sehe ich kein Problem darin den Endpoint NICHT weiter abzuschotten. Ein User darf sich gerne die Reine HTML Seite seines Reports ansehen oder ?

Befürchtest du HTML injection über das Entwickler Tool ?

**Comment by mimischi** [comment]
Nein ich meine, dass die Headless Instanz nichts anderes macht als selbst eine URL aufzurufen. Das heißt allerdings, dass diese Instanz auch als User eingeloggt sein müsste, damit der HTML Report angezeigt wird. Am einfachsten realisieren wir es also, in dem die View nur mit `API_KEY` aufgerufen werden kann. Das stellt immerhin einigermaßen einen Schutz dar.

Darüberhinaus wird der HTML Report auch wirklich nur zur Generierung der PDF erstellt. Ich dachte nicht, dass wir den explizit noch mal ins Frontend einbinden, das wird auch sehr hässlich. Im Frontend soll die Daten des Reports einfach unabhängig vom HTML Report angezeigt werden.

**Comment by chgad** [comment]
Ah jetzt verstehe ich was du mit der Authentifizierung meintest. Ich schaue mir mal an wie man das verwirklichen kann.

**Comment by chgad** [comment]
Planänderung.

Grundkonzept:

- [ ] erstelle ein HTML-Template `report_template.html` welches den aktuellen [Stundenzettel](www.uni-frankfurt.de/68252342/Arbeitszeitkonto_SHK.xlsx) abbildet

- [ ]  erstelle eine View, url : `export_report/<uuid>`

- [ ] Diese View erstellt den Stundenzettel Export mithilfe des Pakets `wkhtmltopdf`und der python library `pdfkit`


Details:

- [ ] Implementiere Check für Überlappende Schichten (ALs Methode der View)
    
    - [ ] Check soll bei Überlapp Error-Response über geben und ALLE überlappenden Schicht Objekte übersgeben.

- [ ] Implementiere Methode die alle Schicht Objekte Tageweise anordnet, Stunden, Pausen etc berechnet.

**Comment by chgad** [comment]
Es müssen laut [codecov](https://codecov.io/gh/ClockGU/clock-backend/pull/39/src/api/views.py) noch mindestens ein Test für die Methoden:

- [ ] `compile_pdf`

- [ ] `calculate_carry_over_hours` mit next_month=False und next_month=True

- [ ] `aggregate_general_content`

- [ ] `aggregate_export_content`

geschrieben werden.

**Comment by chgad** [comment]
Erledigt in #39. Check für überlappende Schichten in #47.
