### ISSUE TITLE
Check für überlappende Schichten

### ISSUE THREAD

**Issue by chgad** [ClockGU/clock-backend#47]
Vor dem export eines Stundenzettel soll überprüft werden ob Schichten existieren welche überlappen.

**Comment by chgad** [comment]
@mimischi Wie soll der Error Response Formatiert sein ?

**Comment by mimischi** [comment]
Etwa in der Art hier?

```
{
  "message": "The shift overlaps with others.",
  "shift": {
    "started": "",
    "stoped": "",
    ...
  },
  "overlapping_shift": {
    "started": "",
    "stopped": "",
    ...
  }
}
```

**Comment by chgad** [comment]
Ich dachte daran, alle überlappenden Schichten auszugeben. 
soetwas wie :

    {
        "message": "There are overlapping shifts.",
        "shifts": [
            [ <shift_1_uuid>, <shift_2_uuid>],
            [<shift_3_uuid>, <shift_4_uuid>],
            [...],
            ...
        ]
    }

Ich weiß nicht ob es wirklich notwenidg ist direkt alle Daten der Schicht mit zuschicken.

**Comment by mimischi** [comment]
Ich finde schon! Geh einfach immer davon aus, dass das Frontend nicht alle aktuellen Daten hat. Dadurch müsste es erst schauen ob die Schichten mit den UUIDs lokal vorhanden sind. Wenn nicht, jede einzeln anfragen.

**Comment by chgad** [comment]
Aber bevor man einen Stundenzettel exportieren kann muss man doch im Kalender gewesen sein, oder ? Dafür wurden ja schon die aktuellsten Schichten angefragt.

**Comment by mimischi** [comment]
So wie es aktuell realisiert ist, nein. Ich sehe kein Problem die paar Byte noch mitzusenden. AFAIK machen das viele REST-Endpunkte genauso. Lieber explizit (und dann lokal normalisieren), anstatt implizit und hoffen, dass lokal schon alle Daten da sind.

**Comment by chgad** [comment]
Ok. Aber trotzdem in dieser Tupel-Form?

**Comment by mimischi** [comment]
Klingt sinnvoll. Sind das immer zweier Tupel? Also wenn Schicht A mit B und C überlappt, gibt es dann zwei Tupel oder nur eins mit drei Einträgen?

**Comment by chgad** [comment]
Es gibt immer 2er Tupel. 
In dem Beispiel von dir würde A mit B und B mit C üperlappen. Der Output wäre [[A,B], [B,C]].
Diese Struktur ergibt sich durch die Logik wie man (in #75) herausfindet ob Schichten überlappen.

**Comment by chgad** [comment]
Erledigt in #75.
