### ISSUE TITLE
Schichten filtern

### ISSUE THREAD

**Issue by mimischi** [ClockGU/clock-backend#55]
Aktuell gibt es den `/api/shifts/list_shifts/<month>/<year>` Endpunkt, der mir alle Schichten eines Monats anzeigt. Allerdings wird hier nicht nach Verträgen unterschieden.

Sinnvoller (und auch RESTful) wäre das hier: `/api/contracts/<uuid>/shifts?year=<year>&month=<month>`.

Mit Hilfe der [Nested relationships](https://www.django-rest-framework.org/api-guide/relations/#nested-relationships) sollten also bei einem `GET` an `/api/contracts/<uuid>/shifts` also ein Vertrag geliefert werden, in dem dazu noch Schichten gelistet sind.

Das Filtering nach Jahr/Monat wird auch von DRF unterstützt: https://www.django-rest-framework.org/api-guide/filtering/

**Comment by chgad** [comment]
1. Ich habe mal gelesen das beide Varianten RESTful seien und ähnliches schon bei anderen Webseiten gesehen.

2. Der Endpoint war für ein "Alle Schichten Dashboard" gedacht in dem man alle Schichten eines Monats unabhängig vom jeweiligen Vertrag sieht (hatten wir mal geplant).

3. Nested relationships ja... und nein. Allgemein kann man das so machen, ich überlege nur gerade ob man so oft direkt alle Schcihten dazu haben will.

**Comment by mimischi** [comment]
>     1. Ich habe mal gelesen das beide Varianten RESTful seien und ähnliches schon bei anderen Webseiten gesehen.
>
>     2. Der Endpoint war für ein "Alle Schichten Dashboard" gedacht in dem man alle Schichten eines Monats unabhängig vom jeweiligen Vertrag sieht (hatten wir mal geplant).

OK! 

>     3. Nested relationships ja... und nein. Allgemein kann man das so machen, ich überlege nur gerade ob man so oft direkt alle Schcihten dazu haben will.

Also ich glaube es ist schon sinnvoll. Per `/api/contracts/<uuid>/` kann man nur den Vertrag abrufen, während `/api/contracts/<uuid>/shifts/` auch alle Schichten zurückgibt. Ich hätte für beide Varianten einen Einsatzzweck im Frontend. Dazu käme dann eben das optionale Filtern via `/api/contracts/<uuid>/shifts?year=<year>&month=<month>`, was die erwarteten Resultate noch weiter einschränkt!

**Comment by chgad** [comment]
Wie kritisch ist das ? Muss es noch vor der closed Beta rein oder reich Open Beta?

**Comment by mimischi** [comment]
Ich kann da erstmal drauf verzichten. Andere Dinge sind da ggf. wichtiger!

**Comment by chgad** [comment]
Closed by #151
