### ISSUE TITLE
Angabe der Stundenzahlen in Minuten

### ISSUE THREAD

**Issue by mimischi** [ClockGU/clock-backend#56]
Ich möchte Vorschlagen, dass alle Stundenzahlen im Backend als Minuten (Integer) abgelegt bzw. ausgegeben werden.

## Verträge
Bei Verträgen wird die Stundenzahl aktuell als Float gespeichert. So wird aus `40:30` also `40.5`. Langfristig habe ich bedenken, dass sich hier irgendwelche Rundungsfehler einschleichen werden. Sinnvoller wäre also das Speichern als Integer (`2430`). Die Umrechnung ist kurzerhand gemacht.

## Reports
Bei Reports ist mir nur die Darstellung wichtig. Aktuell wird vom Endpunkt ein `datetime.timedelta` zurückgegeben im Format `<tage> <stunden>:<minuten>:<sekunden>`. Das muss erst geparsed werden. Einfacher wäre es die `timedelta` Methode `.total_seconds()` zu nutzen. Die Ausgabe kann dann zu Minuten konvertiert werden.

**Comment by chgad** [comment]
Ja das ist auch ein Punkt der mir noch nicht gefällt!

Ich denke dabei aber eher an ein [relativedelta](https://dateutil.readthedocs.io/en/stable/relativedelta.html).

**Comment by mimischi** [comment]
Wenn ich die [SO Antwort](https://stackoverflow.com/a/12433328/4791226) verstehe, dann ist es eigentlich egal ob wir `timedelta` oder `relativedelta` nutzen? In diesem Issue geht es mir aber auch um die Antwort des Backends und nicht um die Darstellung im Code :)

**Comment by chgad** [comment]
Die Representation des relativdelta's ist "besser".

**Comment by mimischi** [comment]
Solange ich in der Reponse einen Integer erhalte, ist mir alles egal 😎

**Comment by chgad** [comment]
Das bedeutet aber, dass ich sehr oft aus Integern dann datetime Objekte machne muss im Backend... Ich fürchte das du deshalb etwas auf dieses Feature waren musst da ich dafür etwas mehr Zeit brauche.

**Comment by mimischi** [comment]
Du brauchst doch effektiv nur eine Funktion schreiben die dir das konvertiert. Aktuell musst du doch das gleiche mit den Floats machen?

**Comment by mimischi** [comment]
Akutes Problem: Erstelle einen Vertrag mit der Angabe `11:11`. Gespeichert wird in der Datenbank  `11.18` als Float. Auf dem Stundenzettel steht als Sollarbeitszeit `11:10.8`.

Wenn die Stunden direkt in Minuten gespeichert werden, müssen wir uns den Kopf nicht mit dem Runden von Zahlen zerbrechen.

**Comment by chgad** [comment]
Ok das nenne ich mal 'nen Edge Case. Aber durchaus berechtigt. Ich würde diesen Punkt momentan dennoch etwas zurückstellen.

**Comment by chgad** [comment]
@mimischi dann wäre eine Umbennenung von `hours` in `minutes` auch sinnvoll.

**Comment by mimischi** [comment]
> @mimischi dann wäre eine Umbennenung von `hours` in `minutes` auch sinnvoll.

Ja, bitte! Ist mit einer Migration wahrscheinlich einfach machbar, oder? Ändert sich was auf API-Seite? Das Feld kommt dann als `minutes ` zurück?
