### ISSUE TITLE
Erweiterung des Report Endpunkts

### ISSUE THREAD

**Issue by mimischi** [ClockGU/clock-backend#57]
Ich verstehe den Nutzen des `/api/reports/get_current/<uuid>` nicht ganz. Führe ich ein `GET` Request durch, erhalte ich folgenden Output:

```
{
  "id": "18cf3b64-bc37-4263-ad1f-9af5ae542f75",
  "month_year": "2019-09-01",
  "hours": "1 18:21:39.715000",
  "created_at": "2019-09-08T20:05:02.938618Z",
  "modified_at": "2019-09-15T07:12:14.996289Z",
  "contract": "42ea6ef5-298d-49ae-9b90-003db528784d"
}
```

Erwarten würde ich allerdings folgendes (Zeitdauerangaben in Minuten):

```
{
  "id": "18cf3b64-bc37-4263-ad1f-9af5ae542f75",
  "month_year": "2019-09-01",
  "haben": "1200",
  "soll": "2400",
  "schichten": [ {schicht_1}, {schicht_2}, ... {schicht_n} ]
  "created_at": "2019-09-08T20:05:02.938618Z",
  "modified_at": "2019-09-15T07:12:14.996289Z",
  "contract": "42ea6ef5-298d-49ae-9b90-003db528784d"
}
```
Damit müsste ich nur einen Request machen und würde alle benötigten Daten erhalten. Die Soll/Haben-Rechnung, genau wie die dazugehörigen Schichten, werden bei der Erstellung des Stundenzettels auch schon genutzt? Also die Logik ist schon da! :)

**Comment by chgad** [comment]
Die Überlegung hinter dem Endpoint ist das Datenvolumen so gering wie möglich zu halten und so wenig wie Möglich Doppelt zu machen.

Die Idee:

1.  User wählt nach Login Vertrag aus. ---> Uuid des relevanten Vertrags ist dem Frontend bekannt
2. User wird in die Kalender/Dashboard Ansicht gebracht.
    - Das Frontend zeigt die Schichten des aktuellen Monats
    - Das Frontend zeigt eine Darstellung des Haben/Soll an.
---> Für die Schichten wird der Endpoint `list-shifts/<month>/<year>/` angefragt (Schcihten jedes Vertrages für diesen Monat)
---> Für Haben/Soll ist der Soll durch den Vertrag bereits bekannt und durch `reports/get_current/<uuid>` wird nur noch das Haben angefragt (*).
Somit muss der Endpoint den Soll nicht mehr mit schicken. Bei dem Punkt der Schichten sehe ich das Problem, dass es keine direkte Report <--> Shift Beziehung gibt. Demnach sollte diese auch nicht in dem Endpoint dargestellt werden.


Zu (*): Sollten in dieser Ansicht nur die Schichten des asugewählten Contracts angezeigt werden muss nach Contract gefiltert werden.
