### ISSUE TITLE
Export aller Nutzerdaten

### ISSUE THREAD

**Issue by chgad** [ClockGU/clock-backend#58]
Die User müssen in der Lage sein alle in Clock gespeicherten Daten, welche sie betreffen, in maschinenlesbarem Zustand zu exportieren.

**Comment by mimischi** [comment]
Kann man hier drauf aufbauen? https://django-import-export.readthedocs.io/en/latest/index.html

**Comment by chgad** [comment]
Ja deshalb das "solution known" label.

**Comment by mimischi** [comment]
Was nicht zwangsläufig heißt, dass du das Paket kanntest :P Aber um so besser -- dann ist das ja sicherlich fix zu implementieren.

**Comment by chgad** [comment]
Vorerst nur ein export als JSON-Datei möglich.
