### ISSUE TITLE
Gestochene Schichten im Backend

### ISSUE THREAD

**Issue by mimischi** [ClockGU/clock-backend#59]
Aktuell sind eingestochene Schichte nur im Frontend abgebildet. Sticht man eine Schicht ein und wechselt das Gerät, so kann man diese eingestochene Schicht auf einem anderen Gerät nicht ausstechen.

Es wäre gut, wenn "eingestochene Schichten" im Backend abgebildet werden könnten. Um es uns einfach zu machen, können wir ein neues Modell `ClockedShift` (oder so) erstellen. Hier brauchen wir pro User auch nur eine einzige Instanz. Im Modell sollte die Startzeit, der User und der Vertrag gespeichert werden. Beim Ausstechen, wird der Eintrag gelöscht und eine normale Schicht (mit einer Endzeit) angelegt.

**Comment by mimischi** [comment]
Ich habe mir mal die Freiheit genommen den Kommentar etwas aufzuräumen :)

Ich finde der Flow klingt sinnvoll. Es bleibt einzig zu klären, wie wir bzgl. "Eine Instanz pro User/Vertrag" verfahren.

@sheepyhollow Wollen wir pro User eine eingestochene Schicht haben oder pro Vertrag eine einzige? Letzteres hieße, pro User könnte es mehrere geben. Das könnte man z.B. nutzen für "Vertag A: Anwesenheit am Campus" und "Vertrag B: HiWi beim Starker Start", bei dem sich User zwei Dinge gleichzeitig tracken. Das eine wäre aber dementsprechend keine Arbeitszeit.

**Comment by sheepyhollow** [comment]
Ich mag ja Flexibilität. Aber Clock soll vor allem Arbeitszeiten tracken und das "gesetzeskonform". Und das erlaubt es (zumindest in diesem Raum-Zeit-Kontinuum) nunmal nicht, eine Arbeitszeit auf zwei Jobs gleichzeitig zu buchen.
Insofern würde ich anregen, das hart zu machen: Pro User darf zu einem Zeitpunkt nur eine Schicht laufen.

**Comment by sheepyhollow** [comment]
Eine Ausnahme könnte der "Default"-Vertrag sein, wie auch immer man den umsetzt. Dort könnte man auch ohne konkreten Vertrag alles mögliche Clocken (aber je nach Umsetzung nichts exportieren).
siehe hier: https://github.com/ClockGU/clock-frontend/issues/27#issue-505175985

**Comment by mimischi** [comment]
Gut, dann würde ich sagen wir regulieren das Ganze einfach _nur_ über das User-Feld -- pro User also nur eine gestochene Schicht.

**Comment by chgad** [comment]
Ich würde es gerne erst restriktiver implementieren. Die Restriktion aufheben ist User freundlicher nachträglich implementiert als sie einzuführen.

Die Thematik Default-Vertrag können wir gerne in einem anderen Issue diskutieren.

**Comment by mimischi** [comment]
"Eine Schicht pro User" ist doch restriktiver als "Eine Schicht pro Vertrag"? Also ich finde wir sollten folgendes machen:

```
user = OneToOneField(User, on_delete=models.CASCADE)
contract = ForeingKey(Contract, on_delete=models.CASCADE)
started = DateTimeField()
id = UUIDField(pk=True)
```

**Comment by mimischi** [comment]
Aber ein `OneToOneField` bei `user` und `contract` ist doch redundant? Das Feld bei `user` wird verhindern, dass zu das gleiche bei einem zweiten Contract erstellen kannst.

**Comment by chgad** [comment]
Allerdings suggeriert ein `ForeignKeyField` eine Many-to-One Relation, die nicht funktionieren würde. Ich wäre hier ganz pythonic für "Explicit is better than implicit."

**Comment by chgad** [comment]
Sollten wir wie bei den anderen Models auch `created_at` und `created_by` speichern?
