### ISSUE TITLE
Konsistenz der API Responses

### ISSUE THREAD

**Issue by mimischi** [ClockGU/clock-backend#81]
Die Formatierungen der API Antworten des gleichen Endpunkts sind sehr unterschiedlich. Dadurch ist das Error handling problematisch.

Wünschenswert wäre ein einheitliches Format das sich durch alle Responses durchzieht, damit man diese einfacher abfangen kann und nicht erst dutzend edge-cases ausprobieren muss umzusehen, welche Responses (in welchem Format) wann kommen können.

Die zwei Beispiele hier beziehen sich beide auf den gleichen Endpunkt `POST /api/shifts/(<uuid>/)` und werden im Frontend in der gleichen Komponente angesprochen.

## Schicht editieren, die bereits exportiert wurde

```
{"detail":"Eine Schicht die bereits exportiert wurde darf nicht modifiziert werden."}
```

## Schicht hinzufügen, in einem Monat der bereits exportiert wurde

```
{"non_field_errors":["Für diesen Monat wurde bereits ein Stundenzettel exportiert.\nEs ist nicht möglich Schichten in diesem Monat zu ändern oder neue zu erstellen. "]}
```

**Comment by chgad** [comment]
First shot: Ich vermute das liegt daran, dass sich [hier](https://github.com/ClockGU/clock-backend/blob/develop/api/serializers.py#L201) eine andere Exception eingeschlichen hat. Ich gehe dem nach.

**Comment by mimischi** [comment]
Eventuell hängt es auch mit den Paketen zusammen die wir nutzen. Ich glaube z.B. das Format der Fehler beim Login sind anders als die beim Erstellen von Schichten.

**Comment by mimischi** [comment]
Mir ist gerade eingefallen, dass eine Liste der möglichen error states sinnvoll wäre. Also effektiv wie die Swagger API aber unter welchen Umständen ein Fehler (und welcher) zurück  kommt.

Aktuell ist das nicht optimal, da ich bei der Implementierung erst erneut an die Sonderfälle denken muss.

**Comment by chgad** [comment]
Als Errorstates sind eigentlich alle HTTP 4XX status codes möglich. Prinzipiell ist alles über die Buisinessrules in der Dokumentation abgebildet. Verstehe ich hier was falsch?

**Comment by mimischi** [comment]
Eventuell sind die Business-Rules schon die richtige Anlaufstelle. Ich schaue noch mal rein, ob das meine Erwartungen in diesem Fall abdeckt.

**Comment by chgad** [comment]
Ich kann allerdings nicht ausschließen, dass die Doku lückenlos ist. Hier muss definitiv noch eine Überarbeitung, auch wenn es nur ein Check ist, stattfinden.

**Comment by mimischi** [comment]
> Ich kann allerdings nicht ausschließen, dass die Doku lückenlos ist.

Genau aus der Befürchtung auch eigentlich die Anfrage. Solange nicht alle Responses dem gleichen Layout folgen, wäre eine Auflistung toll, in der steht: "Bei Anfrage `XYZ` gibt es `HTTP 400` mit der Response `{"abc": "hello", "objects": [...]}`.

Dadurch könnte ich eher sicher gehen, dass ich wirklich alles abdecke.

**Comment by chgad** [comment]
Das ist overhead. Dann rücken wir eher die Überabreitung der Doku in der Priorität nach vorne und klären woher die unterschiedlichen Formate (siehe erster Beitrag) stammen.

Dann sollte klar sein, wie ein Error aussieht und die Serializer sollten durch Swagger klar sein.

**Comment by chgad** [comment]
@mimischi könntest du mal überprüfen ob diese inkonsistenz nachwievor existiert?

**Comment by mimischi** [comment]
Hat sich hier denn schon etwas getan?
