### ISSUE TITLE
Default contract

### ISSUE THREAD

**Issue by sheepyhollow** [ClockGU/clock-backend#86]
In Clock v1 gab es einen Default-Vertrag, bei dem man ohne Umstände sofort clocken konnte.
Das kann aus verschiedenen Gründen praktisch sein.

Ich könnte mir vorstellen, dass man diesen aber nicht exportieren kann.
D.h. wenn ich einen einen Stundenzettel erzeugen will, muss ich einen ordentlichen Vertrag erstellen. Da ich Schichten ja umbuchen kann, wäre das auch zumutbar.

**Comment by mimischi** [comment]
Habe das Issue ins Backend verlagert. Benötigt Diskussionsbedarf, deswegen auch cc @chgad

**Comment by sheepyhollow** [comment]
Mein Argument: man muss nicht durch die 5-Step-Contract-Creation sondern man kann direkt loslegen. Ist ein Vorteil für die Einführung, finde ich. 

Für das nachträgliche Zuordnen zu Contracts wäre allerdings eine Batch-Möglichkeit sinnvoll (vgl. https://github.com/ClockGU/clock-frontend/issues/28#issue-505177387).

**Comment by mimischi** [comment]
Ich denke es ist ein Backend Issue, weil das Backend immer einen Vertrag zur Schicht benötigt.

**Comment by chgad** [comment]
> Mein Argument: man muss nicht durch die 5-Step-Contract-Creation sondern man kann direkt loslegen. Ist ein Vorteil für die Einführung, finde ich.

Sehe ich nicht so. Du verschiebst die Arbeit nur und sogar verschlimmerst sie damit noch. Im nachhinein (bspw.) 20 Schichten auszuwählen und 3 unterschiedlichen Verträgen zuzuordnen scheint mir mehr Arbeit als 3x fünf kurze und mit wenigen klicks abgearbeitete Forms durchzu gehen.

Gegenbeispiel: Stell dir ein MMO vor. Du erstellst deinen Account, und willst jetzt direkt zocken? Nein, das Spiel zwingt dich erst einen Charakter zu erstellen. Das sind die Spielregeln; So kann alles diesem Charakter zugeordnet werden.

**Comment by mimischi** [comment]
Ich denke die Idee mit "default contracts" ist aber auch, dass das Tool dadurch neben Uni-Verträgen automatisch auch x-beliebige Dinge tracken kann. Das passt aktuell natürlich nicht in unser Stundenzettel Framework, ist aber ein nettes Feature.

**Comment by sheepyhollow** [comment]
Wenn man beim allerersten Login einen passenden Dialog anbietet, dann ist es kein "Betrug".

-> "Wir empfehlen Dir, zu Beginn einen Vertrag anzulegen. Du kannst Clock aber auch einfach so nutzen und Deine erfassten Zeiten später einem Vertrag zuordnen."

**Comment by chgad** [comment]
> Das passt aktuell natürlich nicht in unser Stundenzettel Framework, ist aber ein nettes Feature.

Richtig. Ich möchte dieses Framework auch nicht aufbohren. Prinzipiell kann man auch jetzt schon alles tracken: Erstelle bspw. einen Vertrag "Sport" und erstelle Shifts dazu wann imer du "Sport" machst. Verbieten wir ja nicht.

> Wenn man beim allerersten Login einen passenden Dialog anbietet, dann ist es kein "Betrug".

Nur weil du es einem HiWi explizit sagst ersparst du ihm im Nachhinein nicht die mehr Arbeit.

**Comment by chgad** [comment]
@sheepyhollow und ich sind zuletzt in einem Gespräch dabei verblieben, dass wir keinen "Default Contract" in dem hier vorgeschlagenen Umfang. 

Grund:
Wir sollten uns bei den User-Stories zwar darauf konzentrieren die Nutzung dem User so einfach und elegeant wie möglich zu machen, aber auch keine falsche Versprechungen oder "lazy junktions" einzubauen. Der Default Contract erscheint dem User prizipiell einfacher als erst einen richtigen Contract zu erstellen, erspart ihm nach mehrfachem Stechen aber nicht die Arbeit des Zuordnens zu dem Contract den er so oder so noch erstellen muss. Ferner kann man eine gewisse Vorarbeit  (4-5 Schritte zum Contract-Erstellen) durchaus erwarten. Bei dem jetzigen Excell-Format ist es schließlich Monatliches eintragen von Datum, Personalnummer, Institut etc. . Betrachtet man darüber hinaus, dass wir planen/hoffen, dass Clock DAS TOOL zum Stundenzettel führen an der GU und somit verpflichtend wird, wäre das Argument "Wenn ich erst sowas machen muss, dann nutze ich es nicht!" auch äußerst schwach. 

Somit würde ich dieses Issue gerne schließen.
Nichts destotrotz kam im Gespräch eine andere Art von "Default Contract" zur Sprache:
Ein Vertrag, der angelegt wurde, aber beim Login sofort ausgewählt wird. Dies erspart gerade Hiwi's mit nur einem Vertrag, oder Hiwi's die mehrheitlich für einen Vertrag arbeiten, das ständige auswählen des Vertrags. Implementierung wäre ein `is_default=Boolean(default=False)` Feld im Contract model. Dazu würde ich nochmal separat ein Issue anlegen.
