### ISSUE TITLE
Löschung/Archivierung inaktiver Accounts

### ISSUE THREAD

**Issue by sheepyhollow** [ClockGU/clock-backend#87]
Wenn Hilfskräfte per Exmatrikulation ausscheiden müssen die Daten eigentlich nicht mehr vorgehalten werden. Wie könnte man hier in Zukunft vorgehen?

Möglichkeit 
- Prüfung nach Aktivität (je Semester) + Erinnerung
- Prüfung, ob HRZ-Account noch existiert (je Semester)

**Comment by mimischi** [comment]
Wenn sich die User per LDAP bei uns anmelden, werden wir intern Accounts für sie anlegen. Wir sollten dann periodisch prüfen, ob der LDAP User noch vorhanden ist. Falls das nicht der Fall ist, sollten wir die User darüber benachrichtigen, dass ihr Account ausläuft und an einem bestimmten Datum gelöscht wird.

Wir könnten Usern noch die Möglichkeit geben weitere Mails (+ein Passwort für Clock) zu hinterlegen, damit der Account aus der LDAP-Routine raus gelöst wird. So funktioniert das auch bei allen möglichen Seiten bei denen man Accounts mit Google/Facebook/GitHub/etc anlegen kann. Zu erst existiert kein Passwort und man loggt sich dauernd über die Dritt-Anbieter ein. Nachträglich kann man ein Passwort einrichten, wodurch man sich mit Mail+Passwort einloggen kann.

**Comment by sheepyhollow** [comment]
Ja, klingt gut.

**Comment by sheepyhollow** [comment]
Nochmal überlegt... ich würde diese Option mit der Fortführung des Accounts nicht ins VVZ schreiben. Das erzeugt nur "Kopfkratzen" und ggf. Argumentationsdruck. Das kann man sich immer noch vorbehalten. Ich finde es wichtiger, auf die Löschung einzugehen.

**Comment by sheepyhollow** [comment]
Ich werde folgende Formulierung einfügen:

> Die o.g. Nutzerdaten werden mit dem Verzeichnisdienst regelmäßig abgeglichen und nach 6 Monaten gelöscht, wenn der zugehörige HRZ-Account nicht mehr existiert. Die Nutzer können ihren Account und damit alle Daten jederzeit selbstständig löschen.

**Comment by mimischi** [comment]
Klingt gut!

**Comment by chgad** [comment]
Da wir mittlerweile weg von LDAP sind, ist das Issue zwar noch aktuell nur haben wir keine Möglichkeit die Existenz von Usern an der Uni zu überprüfen.

@sheepyhollow 
Was sind die Löschungsfristen?
Wie weit vor Ablauf der Frist (gesehen vom `last_login`) wollen wir eine Nachricht an den User schicken?

**Comment by sheepyhollow** [comment]
> nur haben wir keine Möglichkeit die Existenz von Usern an der Uni zu überprüfen.

True. Angenommen wir könnten - wie würde das konzeptuell aussehen? Würde ein Job regelmäßig prüfen, welche Accounts noch aktiv sind? Vielleicht wäre es möglich, als Auth-Attribut (Userinfo) auch die Gültigkeitsdauer des Accounts geliefert zu bekommen.

> Was sind die Löschungsfristen?

Laut [hess. Immatrikulationsverordnung §15 Abs. 2](https://www.lexsoft.de/cgi-bin/lexsoft/lexsoft.cgi?chosenIndex=13519&templateID=document&task=fliesstext&xid=3943015,1,20170225) sind personenbezogene Daten _innerhalb eines Jahres_ nach Exmatrikulation zu löschen.

Laut [Art. 17 DSGVO](https://dsgvo-gesetz.de/art-17-dsgvo/) müssen personenbezogene Daten gelöscht werden, sobald sie für den Zweck der Erhebung nicht mehr nötig sind. Wenn man das streng auslegt, wäre das eigentlich nach Abgabe des Stundenzettels; das wäre aber nicht convenient, zumal die AZK-Daten ja vom User aktiv und freiwillig in Clock eingegeben werden (äquivalent zum Ablegen einer Tabelle in der Hessenbox). Daher würde ich mich an der o.g. Jahresfrist orientieren.

Die _Aufbewahrungsfristen_ für Arbeitszeitdaten nach §17 MiLog (max. 2 Jahre) betrifft uns nicht, da wir die AZK-Daten nicht speichern, um sie (als Arbeitgeber) zu speichern. Diese Fristen beziehen sich auf die Stundenzettel.

> Wie weit vor Ablauf der Frist (gesehen vom last_login) wollen wir eine Nachricht an den User schicken?

Nicht sicher, ob ich die Frage richtig verstehe. Die 1-Jahresfrist bezieht sich auf nach Exma. Ich meine, dass der Login noch 6 Wochen nach Exma möglich ist. Das ist der späteste Zeitpunkt für den `last_login`.

**Comment by chgad** [comment]
> Vielleicht wäre es möglich, als Auth-Attribut (Userinfo) auch die Gültigkeitsdauer des Accounts geliefert zu bekommen.

Könnte funktionieren, aber ich weiß nicht ob sich die Daten updaten würden wenn man noch als "logged in" im CAS gilt

**Comment by sheepyhollow** [comment]
Good point, wahrscheinlich nicht. Wenn ein User Clock regelmäßig nutzt, muss er sich nur sehr selten neu authentifizieren.
Und alles andere wäre vermutlich kompliziert (eine Reaktion, wenn das Datum erreicht ist.)

**Comment by chgad** [comment]
Müsste ich mal mit Herrn Specker drüber reden A) ob wir die Daten mit OAuth überhauptbekommen B) Wie sieht es mit änderungen auf HRZ-Seite aus
