### ISSUE TITLE
Fehlermeldung bei zweitgestochener Schicht

### ISSUE THREAD

**Issue by mimischi** [ClockGU/clock-backend#91]
Ist für den User schon eine Schicht eingestochen (`ClockedInShift`) und probiert man mit `POST` erneut eine via `/api/clockedinshifts/` zu erstellen, kriege ich folgende Fehlermeldung:

```
{"user":["This field must be unique."],"contract":["This field must be unique."]}
```

Auch wenn der Fall im Frontend nicht auftreten sollte, leite ich alle Fehlermeldungen der API direkt an den User weiter. Die hier ist zu kryptisch, da sie etwas über unsere Implementation aussagt und nicht über das Problem ("Du darfst nicht in zwei Schichten gleichzeitig eingestochen sein", o.ä.).

related #81

**Comment by chgad** [comment]
Was meinst du mit "eine zweite Schicht"?

**Comment by mimischi** [comment]
Habe den Post oben aktualisiert und erweitert.

**Comment by mimischi** [comment]
Der Fehler kann im Frontend _doch_ auftreten:

1) Auf Gerät A Seite besuchen. Hier ist keine Schicht gestochen.
2) Auf Gerät B einstechen. Nun ist eine Schicht gestochen.
3) Auf Gerät A probieren einzustechen. Der "kryptische" Fehler tritt auf.

**Comment by chgad** [comment]
> {"user":["This field must be unique."],"contract":["This field must be unique."]}

Das ist das gegebene standart Format für Fehlerausgaben bei 'nem 400 - BAD REQUEST. Man bekommt alle, betroffenen Felder mit jeweils einer Liste aller Fehlermeldungen. Da in diesem Beispiel genau der Fall eintritt "Es darf nur eine gestochene Schicht existieren" würde ich den Fehler nicht als Kryptisch bezeichenen; eher als Nutzer-unfreundlich.

Könnte man das nicht durch eine Änderung des Workflows abfangen?
Beispiel für den Workflow:
> 
  1.  Auf Gerät A Seite besuchen. Hier ist keine Schicht gestochen.
  2.  Auf Gerät B einstechen. Nun ist eine Schicht gestochen.
  3.  Auf Gerät A probieren einzustechen. Der "kryptische" Fehler tritt auf.

Statt den User im dritten Schritt des Szenarios direkt einstechen zu lassen, erst nochmal überprüfen ob nicht doch schon eine Schicht bereits eingestochen ist.

**Comment by mimischi** [comment]
Das wäre möglich, aber dann wird das im 2. Schritt ja auch passieren und dadurch also jedes mal wenn man eine Schicht einsticht. Ich sehe hier eher das Problem, das wir recht viele roundtrips machen und der User dadurch lange wartet.

Allerdings muss ich, bei dem Fehler, ja tatsächlich trotzdem ein `GET` machen um das Frontend auf den aktuellsten Stand zu bringen. Also entweder passiert das `GET` wirklich immer oder eben "nur", wenn der Fehler kommt.

**Comment by chgad** [comment]
> Das wäre möglich, aber dann wird das im 2. Schritt ja auch passieren und dadurch also jedes mal wenn man eine Schicht einsticht. Ich sehe hier eher das Problem, das wir recht viele roundtrips machen und der User dadurch lange wartet.

Wenn wir es mal anders betrachten kommen wir vielleicht auf eine einheitliche Definition.

Gehen wir erstmal von folgendenm Szenario aus:

1. Auf Gerät A wird die Seite geöffnet und keine eingestochene Schicht existiert.
2. Auf Gerät B wird die Seite geöffnet und keine eingestochene Schicht existiert.
3. Der User sticht auf Gerät B ein. Ab jetzt existiert eine eingestochene Schichte.
4. Der User bedient nun wieder Gerät A...

Wenn wir den Gerätewechsel als impliziten Neu-Aufruf der Seite betrachten, wäre es doch logisch vor einem Einstechen das Clocked-In-UI zu aktualisieren. 

> [...] das wir recht viele roundtrips machen und der User dadurch lange wartet.

Dauert der `GET` Request so lange? Vorallem, ist es ein kleiner Request mehr.

> Immer anzufragen fühlt sich aber trotzdem irgendwie merkwürdig an. Das Backend soll hier ja entscheiden ob ich etwas machen darf.

Wenn du da Backend entscheiden lassen willst musst du wie gesagt 

> Also entweder passiert das GET wirklich immer oder eben "nur", wenn der Fehler kommt.

zweiteres tun.

Um diese extra Abfrage kämen wir nur herum wenn wir Web-Sockets implementieren, was ich bis jetzt, für eine kleine Abfrage nicht gerechtfertigt sehe.

**Comment by mimischi** [comment]
Für mich ist der Punkt wie folgt:

**Situation A**

1) User klickt auf "Clock in" und UI macht ein `POST /api/clockedinshifts/`.
2) Backend gibt diesen Fehler zurück.
3) UI macht einen `GET /api/clockedinshifts/`.
4) Eingestochene Schicht erscheint.

**Situation B**

1) User klickt auf "Clock in" und UI macht zuerst ein `GET /api/clockedinshifts`.
  a) Wenn hier 404 zurück kommt, folgt ein `POST /api/clockedinshifts/`.
  b) Kommt hier 200 zurück, wird die Schicht angezeigt.

Ich sehe das Problem bei B eben, dass das bei jedem Stechen passieren wird, also für jeden User immer. Langfristig ist das ein Request mehr als man notwendigerweise machen muss, da man sich diesen wie in A meist sparen kann. Wir würden also für diesen Case (weiß nicht wie häufig das auftreten wird) alle User zu dieser Lösung zwingen.

Letztendlich ist es tatsächlich nur ein Request und für jetzt wahrscheinlich nicht so schlimm. Ich kann das auch erstmal so implementieren, da das schnell gelöst sein sollte, aber so ganz sauber erscheint mir die Lösung irgendwie nicht.

**Comment by chgad** [comment]
Fällt dir denn etwas ein, wie man es anders lösen kann?

**Comment by chgad** [comment]
Kann man das Issue als gelöst betrachten @mimischi ?

**Comment by mimischi** [comment]
Ja, kann man schließen. Ich öffne mir ein Referenz-Issue im Frontend auf, damit ich die Diskussion hier leichter finde.
