### ISSUE TITLE
API Response Sprache

### ISSUE THREAD

**Issue by mimischi** [ClockGU/clock-backend#96]
Das Frontend stellt Fehlernachrichten des Backends unverändert wieder. Einige sind durch z.B. das `djoser` Paket auf Englisch. Hier wäre es gut, wenn die API einen `LANGUAGE` Header (o.ä.) entgegen nehmen würde, um auch die Sprache der Response korrekt (also Englisch oder Deutsch) zu setzen.

~Ich hab gerade jetzt nicht geschaut, meine aber das DRF so etwas kann.~ DRF kann so etwas auch: https://www.django-rest-framework.org/topics/internationalization/

**Comment by sheepyhollow** [comment]
d.h. da muss nichts manuell übersetzt werden, da gibt es Pakete?

**Comment by mimischi** [comment]
Ich meinte, dass im HTTP Standard schon eingebaut ist die User-Sprache mitzuliefern (wie sonst weiß eine Seite welche Sprache du/dein Betriebssystem/der Browser spricht). DRF sollte genau den HTTP Header auslesen können (meine Annahme).

Da wir ein paar eigene Fehlermeldungen haben, müssen wir diese aber tatsächlich auch noch manuell übersetzen. Eventuell kann @chgad hier ein paar Pointer geben wo man genau schauen muss.

**Comment by chgad** [comment]
Ja, dann müssen die Custom Feher von uns auch übersetzt werden, folglich müssen wir Rosetta benutzen.

**Comment by chgad** [comment]
Ich nehme mal an Deutsch und Englisch genügen für's erste als Sprachen.

**Comment by mimischi** [comment]
Ja, mehr haben wir auch erstmal nicht vor zu übersetzten!

**Comment by chgad** [comment]
Done in #105
