### ISSUE TITLE
Spracheinstellung des Users

### ISSUE THREAD

**Issue by mimischi** [ClockGU/clock-backend#98]
Verwandt mit #96, sollte ein User in einem eigenen Profil die Sprache der Seite einstellen können.  Diese Info würde ich dann im Frontend abgreifen, um die generelle Lokalisierung einzustellen.

**Comment by chgad** [comment]
Sprich ein `language` Feld im User Model?

**Comment by mimischi** [comment]
Ja das wäre super. `de` und `en` sollten erstmal die einzigen auswählbaren Dinge sein.

**Comment by chgad** [comment]
Done in #102
